"""
Embedding Engine Module
Provides multi-backend embedding generation with persistent caching and zero-failure fallbacks.
"""

import os
import json
import pickle
import logging
import hashlib
from typing import List, Optional, Dict, Any
import numpy as np

from .config import RAGConfig, default_config

logger = logging.getLogger("NetGuardAI.RAG.Embeddings")


class EmbeddingEngine:
    """Multi-backend embedding system with on-disk caching."""

    def __init__(self, config: Optional[RAGConfig] = None):
        self.config = config or default_config
        self.provider = self.config.EMBEDDING_PROVIDER.lower()
        self.cache_file = self.config.CACHE_DIR / "embedding_cache.pkl"
        self.vectorizer_file = self.config.CACHE_DIR / "tfidf_vectorizer.pkl"
        # The old cache can contain vectors generated by a different provider/model.
        # Do not reuse it for retrieval; this prevents 384-d vs 1024-d mismatches.
        self._cache: Dict[str, List[float]] = {}
        self._tfidf_vectorizer = self._load_tfidf_vectorizer()
        self._sentence_transformer_model = None
        self._initialized = False

    def _load_cache(self) -> Dict[str, List[float]]:
        """Loads persistent embedding cache from disk."""
        if self.cache_file.exists():
            try:
                with open(self.cache_file, "rb") as f:
                    return pickle.load(f)
            except Exception as e:
                logger.warning(f"Failed to load embedding cache: {e}. Starting fresh.")
        return {}

    def _load_tfidf_vectorizer(self):
        """Load the fitted TF-IDF vectorizer used by an existing TF-IDF index."""
        if self.vectorizer_file.exists():
            try:
                with open(self.vectorizer_file, "rb") as f:
                    return pickle.load(f)
            except Exception as e:
                logger.warning(f"Failed to load TF-IDF vectorizer: {e}")
        return None

    def _save_tfidf_vectorizer(self):
        """Persist the fitted TF-IDF vectorizer so query embeddings use the same vocabulary."""
        if self._tfidf_vectorizer is None:
            return
        try:
            with open(self.vectorizer_file, "wb") as f:
                pickle.dump(self._tfidf_vectorizer, f)
        except Exception as e:
            logger.warning(f"Failed to persist TF-IDF vectorizer: {e}")

    def _save_cache(self):
        """Saves embedding cache to disk."""
        try:
            with open(self.cache_file, "wb") as f:
                pickle.dump(self._cache, f)
        except Exception as e:
            logger.warning(f"Failed to persist embedding cache: {e}")

    def _get_text_hash(self, text: str) -> str:
        return hashlib.sha256(text.encode("utf-8")).hexdigest()

    def fit_corpus(self, corpus_texts: List[str]):
        """Fits internal vectorizer (e.g. TF-IDF) if using hybrid or auto mode."""
        if not corpus_texts:
            return

        try:
            from sklearn.feature_extraction.text import TfidfVectorizer
            # Character + word n-grams for cybersecurity terms (e.g., "syn-ack", "slowloris", "dst_host")
            self._tfidf_vectorizer = TfidfVectorizer(
                ngram_range=(1, 2),
                max_features=1024,
                sublinear_tf=True,
                token_pattern=r"(?u)\b\w[\w-]+\w\b|\b\w+\b",
            )
            self._tfidf_vectorizer.fit(corpus_texts)
            self._save_tfidf_vectorizer()
            self._initialized = True
            logger.info("TF-IDF Vectorizer successfully fitted on corpus.")
        except Exception as e:
            logger.error(f"Error fitting TF-IDF vectorizer: {e}")

    def embed_texts(self, texts: List[str]) -> np.ndarray:
        """Embeds a list of texts into normalized float32 vectors."""
        if not texts:
            return np.empty((0, self.config.EMBEDDING_DIMENSION), dtype=np.float32)

        # Check if all texts are cached
        cached_vectors = []
        uncached_indices = []
        uncached_texts = []

        for idx, text in enumerate(texts):
            thash = self._get_text_hash(text)
            if thash in self._cache:
                cached_vectors.append((idx, np.array(self._cache[thash], dtype=np.float32)))
            else:
                uncached_indices.append(idx)
                uncached_texts.append(text)

        if not uncached_texts:
            # Sort by original index and return
            cached_vectors.sort(key=lambda x: x[0])
            return np.array([v[1] for v in cached_vectors], dtype=np.float32)

        # Generate embeddings for uncached texts
        new_embeddings = self._generate_embeddings(uncached_texts)

        # Update cache
        for text, emb in zip(uncached_texts, new_embeddings):
            thash = self._get_text_hash(text)
            self._cache[thash] = emb.tolist()
        self._save_cache()

        # Combine cached and newly computed embeddings in original order
        all_embeddings = [None] * len(texts)
        for idx, emb in cached_vectors:
            all_embeddings[idx] = emb
        for idx, emb in zip(uncached_indices, new_embeddings):
            all_embeddings[idx] = emb

        return np.array(all_embeddings, dtype=np.float32)

    def embed_query(self, query: str) -> np.ndarray:
        """Generate a fresh query embedding; never reuse stale cross-provider cache entries."""
        if not query:
            return np.zeros(self.config.EMBEDDING_DIMENSION, dtype=np.float32)
        try:
            result = self._generate_embeddings([query])
            return result[0]
        except Exception as e:
            logger.error(f"Query embedding failed: {e}")
            return np.zeros(self.config.EMBEDDING_DIMENSION, dtype=np.float32)

    def _generate_embeddings(self, texts: List[str]) -> np.ndarray:
        """Dispatches embedding generation to configured or auto-selected provider."""
        # 1. Try sentence-transformers if specified or auto
        if self.provider in ("sentence_transformers", "auto"):
            emb = self._try_sentence_transformers(texts)
            if emb is not None:
                return emb

        # 2. Try Gemini API if key is present
        if (self.provider == "gemini" or (self.provider == "auto" and self.config.GEMINI_API_KEY)) and self.config.GEMINI_API_KEY:
            emb = self._try_gemini_embeddings(texts)
            if emb is not None:
                return emb

        # 3. Try OpenAI API if key is present
        if (self.provider == "openai" or (self.provider == "auto" and self.config.OPENAI_API_KEY)) and self.config.OPENAI_API_KEY:
            emb = self._try_openai_embeddings(texts)
            if emb is not None:
                return emb

        # 4. Reliable Default: TF-IDF + Cosine Normalization
        return self._generate_tfidf_embeddings(texts)

    def _try_sentence_transformers(self, texts: List[str]) -> Optional[np.ndarray]:
        try:
            if self._sentence_transformer_model is None:
                from sentence_transformers import SentenceTransformer
                self._sentence_transformer_model = SentenceTransformer(self.config.EMBEDDING_MODEL_NAME)
            embeddings = self._sentence_transformer_model.encode(texts, normalize_embeddings=True)
            return np.array(embeddings, dtype=np.float32)
        except Exception:
            return None

    def _try_gemini_embeddings(self, texts: List[str]) -> Optional[np.ndarray]:
        try:
            import requests
            url = f"https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?key={self.config.GEMINI_API_KEY}"
            requests_payload = {
                "requests": [{"model": "models/text-embedding-004", "content": {"parts": [{"text": t}]}} for t in texts]
            }
            resp = requests.post(url, json=requests_payload, timeout=20)
            if resp.status_code == 200:
                data = resp.json()
                raw_emb = [item["values"] for item in data.get("embeddings", [])]
                emb_arr = np.array(raw_emb, dtype=np.float32)
                # L2 normalize
                norms = np.linalg.norm(emb_arr, axis=1, keepdims=True)
                norms[norms == 0] = 1.0
                return emb_arr / norms
        except Exception as e:
            logger.warning(f"Gemini embedding failed: {e}")
        return None

    def _try_openai_embeddings(self, texts: List[str]) -> Optional[np.ndarray]:
        try:
            import requests
            url = "https://api.openai.com/v1/embeddings"
            headers = {"Authorization": f"Bearer {self.config.OPENAI_API_KEY}", "Content-Type": "application/json"}
            resp = requests.post(url, headers=headers, json={"input": texts, "model": "text-embedding-3-small"}, timeout=20)
            if resp.status_code == 200:
                data = resp.json()
                raw_emb = [item["embedding"] for item in data.get("data", [])]
                return np.array(raw_emb, dtype=np.float32)
        except Exception as e:
            logger.warning(f"OpenAI embedding failed: {e}")
        return None

    def _generate_tfidf_embeddings(self, texts: List[str]) -> np.ndarray:
        """Guaranteed built-in fallback using scikit-learn TF-IDF + dense normalization."""
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.preprocessing import normalize

        if self._tfidf_vectorizer is None:
            self._tfidf_vectorizer = TfidfVectorizer(
                ngram_range=(1, 2),
                max_features=1024,
                sublinear_tf=True,
                token_pattern=r"(?u)\b\w[\w-]+\w\b|\b\w+\b",
            )
            # Self-fit on provided texts if not previously fitted
            self._tfidf_vectorizer.fit(texts)
            self._save_tfidf_vectorizer()

        try:
            sparse_matrix = self._tfidf_vectorizer.transform(texts)
        except Exception:
            # Re-fit if new vocabulary encountered
            self._tfidf_vectorizer.fit(texts)
            sparse_matrix = self._tfidf_vectorizer.transform(texts)

        dense_matrix = sparse_matrix.toarray().astype(np.float32)
        # Normalize to unit length for exact cosine similarity
        normed = normalize(dense_matrix, norm="l2", axis=1)
        return normed
